#pragma once
#include "Widgets.hpp"
void OnImGui_SceneGraphWidget_SceneStaticMeshComponentWidget(SceneStaticMeshComponent*);
void OnImGui_SceneGraphWidget_SceneSkinnedMeshComponentWidget(SceneSkinnedMeshComponent*);
void OnImGui_SceneGraphWidget_SceneLightComponentWidget(SceneLightComponent*);
void OnImGui_SceneGraphWidget_SceneCameraComponentWidget(SceneCameraComponent*);
void OnImGui_SceneGraphWidget_SceneArmatureComponentWidget(SceneArmatureComponent* armature);

