// Generated by Scripts/OCIOBakeLUTs.py
// OCIO config: E:\Foundation\Scripts\blender-5-1-colormanagement\config.ocio
#pragma once
#include <cstdint>

struct ViewLUTEntry
{
    const char* label;
    const char* path;
};

inline constexpr ViewLUTEntry kViewLUTsSdr[] = {
    {"Standard / No Look", "data/assets/view_lut_sdr_standard_no_look.dds"},
    {"ACES 1.3 / No Look", "data/assets/view_lut_sdr_aces_1_3_no_look.dds"},
    {"ACES 1.3 / ACES 1.3 - Reference Gamut Compression", "data/assets/view_lut_sdr_aces_1_3_look_aces_1_3_reference_gamut_compression.dds"},
    {"ACES 2.0 / No Look", "data/assets/view_lut_sdr_aces_2_0_no_look.dds"},
    {"ACES 2.0 / ACES 2.0 - Reference Gamut Compression", "data/assets/view_lut_sdr_aces_2_0_look_aces_2_0_reference_gamut_compression.dds"},
    {"AgX / No Look", "data/assets/view_lut_sdr_agx_no_look.dds"},
    {"AgX / AgX - Punchy", "data/assets/view_lut_sdr_agx_look_agx_punchy.dds"},
    {"AgX / AgX - Greyscale", "data/assets/view_lut_sdr_agx_look_agx_greyscale.dds"},
    {"AgX / AgX - Very High Contrast", "data/assets/view_lut_sdr_agx_look_agx_very_high_contrast.dds"},
    {"AgX / AgX - High Contrast", "data/assets/view_lut_sdr_agx_look_agx_high_contrast.dds"},
    {"AgX / AgX - Medium High Contrast", "data/assets/view_lut_sdr_agx_look_agx_medium_high_contrast.dds"},
    {"AgX / AgX - Base Contrast", "data/assets/view_lut_sdr_agx_look_agx_base_contrast.dds"},
    {"AgX / AgX - Medium Low Contrast", "data/assets/view_lut_sdr_agx_look_agx_medium_low_contrast.dds"},
    {"AgX / AgX - Low Contrast", "data/assets/view_lut_sdr_agx_look_agx_low_contrast.dds"},
    {"AgX / AgX - Very Low Contrast", "data/assets/view_lut_sdr_agx_look_agx_very_low_contrast.dds"},
    {"Filmic / No Look", "data/assets/view_lut_sdr_filmic_no_look.dds"},
    {"Filmic / Very High Contrast", "data/assets/view_lut_sdr_filmic_look_very_high_contrast.dds"},
    {"Filmic / High Contrast", "data/assets/view_lut_sdr_filmic_look_high_contrast.dds"},
    {"Filmic / Medium High Contrast", "data/assets/view_lut_sdr_filmic_look_medium_high_contrast.dds"},
    {"Filmic / Medium Contrast", "data/assets/view_lut_sdr_filmic_look_medium_contrast.dds"},
    {"Filmic / Medium Low Contrast", "data/assets/view_lut_sdr_filmic_look_medium_low_contrast.dds"},
    {"Filmic / Low Contrast", "data/assets/view_lut_sdr_filmic_look_low_contrast.dds"},
    {"Filmic / Very Low Contrast", "data/assets/view_lut_sdr_filmic_look_very_low_contrast.dds"},
};

inline constexpr int kViewLUTSdrCount = static_cast<int>(sizeof(kViewLUTsSdr) / sizeof(kViewLUTsSdr[0]));
inline constexpr int kDefaultViewLUTSdr = 1;

inline constexpr ViewLUTEntry kViewLUTsHdr[] = {
    {"Standard / No Look", "data/assets/view_lut_hdr_standard_no_look.dds"},
    {"ACES 1.3 - HDR 1000 nits / No Look", "data/assets/view_lut_hdr_aces_1_3_hdr_1000_nits_no_look.dds"},
    {"ACES 1.3 - HDR 1000 nits / ACES 1.3 - Reference Gamut Compression", "data/assets/view_lut_hdr_aces_1_3_hdr_1000_nits_look_aces_1_3_reference_gamut_compression.dds"},
    {"ACES 2.0 - HDR 1000 nits / No Look", "data/assets/view_lut_hdr_aces_2_0_hdr_1000_nits_no_look.dds"},
    {"ACES 2.0 - HDR 1000 nits / ACES 2.0 - Reference Gamut Compression", "data/assets/view_lut_hdr_aces_2_0_hdr_1000_nits_look_aces_2_0_reference_gamut_compression.dds"},
    {"AgX - HDR 1000 nits / No Look", "data/assets/view_lut_hdr_agx_hdr_1000_nits_no_look.dds"},
    {"AgX - HDR 1000 nits / AgX - Punchy", "data/assets/view_lut_hdr_agx_hdr_1000_nits_look_agx_punchy.dds"},
    {"AgX - HDR 1000 nits / AgX - Greyscale", "data/assets/view_lut_hdr_agx_hdr_1000_nits_look_agx_greyscale.dds"},
    {"AgX - HDR 1000 nits / AgX - Very High Contrast", "data/assets/view_lut_hdr_agx_hdr_1000_nits_look_agx_very_high_contrast.dds"},
    {"AgX - HDR 1000 nits / AgX - High Contrast", "data/assets/view_lut_hdr_agx_hdr_1000_nits_look_agx_high_contrast.dds"},
    {"AgX - HDR 1000 nits / AgX - Medium High Contrast", "data/assets/view_lut_hdr_agx_hdr_1000_nits_look_agx_medium_high_contrast.dds"},
    {"AgX - HDR 1000 nits / AgX - Base Contrast", "data/assets/view_lut_hdr_agx_hdr_1000_nits_look_agx_base_contrast.dds"},
    {"AgX - HDR 1000 nits / AgX - Medium Low Contrast", "data/assets/view_lut_hdr_agx_hdr_1000_nits_look_agx_medium_low_contrast.dds"},
    {"AgX - HDR 1000 nits / AgX - Low Contrast", "data/assets/view_lut_hdr_agx_hdr_1000_nits_look_agx_low_contrast.dds"},
    {"AgX - HDR 1000 nits / AgX - Very Low Contrast", "data/assets/view_lut_hdr_agx_hdr_1000_nits_look_agx_very_low_contrast.dds"},
};

inline constexpr int kViewLUTHdrCount = static_cast<int>(sizeof(kViewLUTsHdr) / sizeof(kViewLUTsHdr[0]));
inline constexpr int kDefaultViewLUTHdr = 1;
