# /// script
# requires-python = ">=3.11,<3.12"
# dependencies = [
#   "numpy",
#   "opencolorio",
# ]
# ///

from __future__ import annotations

import argparse
import re
from pathlib import Path

import PyOpenColorIO as ocio  # type: ignore[reportMissingImports]

from OCIOBakeLUTs import DEFAULT_INPUT_SPACE, DEFAULT_LUT_SIZE, create_config, main as bake_ocio_lut_main

FOUNDATION_OCIO_CONFIG = Path(__file__).resolve().parent / "blender-5-1-colormanagement" / "config.ocio"
DDS_OUTPUT_DIR = Path(__file__).resolve().parent.parent / "Editor" / "Render" / "Data"
VIEW_LUTS_HEADER_PATH = Path(__file__).resolve().parent.parent / "Editor" / "Render" / "ViewLUTs.hpp"

LUT_OUTPUTS = [
    {
        "kind": "sdr",
        "display": "sRGB",
        "default_view": "ACES 1.3",
        "default_look": None,
        "array_name": "kViewLUTsSdr",
        "count_name": "kViewLUTSdrCount",
        "default_name": "kDefaultViewLUTSdr",
    },
    {
        "kind": "hdr",
        "display": "Rec.2100-PQ",
        "default_view": "ACES 2.0 - HDR 500 nits",
        "default_look": None,
        "array_name": "kViewLUTsHdr",
        "count_name": "kViewLUTHdrCount",
        "default_name": "kDefaultViewLUTHdr",
    },
]

FILMIC_LOOKS = [
    "Very High Contrast",
    "High Contrast",
    "Medium High Contrast",
    "Medium Contrast",
    "Medium Low Contrast",
    "Low Contrast",
    "Very Low Contrast",
]

AGX_LOOKS = [
    "AgX - Punchy",
    "AgX - Greyscale",
    "AgX - Very High Contrast",
    "AgX - High Contrast",
    "AgX - Medium High Contrast",
    "AgX - Base Contrast",
    "AgX - Medium Low Contrast",
    "AgX - Low Contrast",
    "AgX - Very Low Contrast",
]

LUT_SELECTIONS: dict[str, list[tuple[str, list[str | None]]]] = {
    "sdr": [
        ("Standard", [None]),
        ("ACES 1.3", [None, "ACES 1.3 - Reference Gamut Compression"]),
        ("ACES 2.0", [None, "ACES 2.0 - Reference Gamut Compression"]),
        ("AgX", [None, *AGX_LOOKS]),
        ("Filmic", [None, *FILMIC_LOOKS]),
    ],
    "hdr": [
        ("Standard", [None]),
        ("ACES 1.3 - HDR 1000 nits", [None, "ACES 1.3 - Reference Gamut Compression"]),
        ("ACES 2.0 - HDR 500 nits", [None, "ACES 2.0 - Reference Gamut Compression"]),
        ("ACES 2.0 - HDR 1000 nits", [None, "ACES 2.0 - Reference Gamut Compression"]),
        ("AgX - HDR 1000 nits", [None, *AGX_LOOKS]),
    ],
}


def _slug(value: str) -> str:
    return re.sub(r"_+", "_", re.sub(r"[^a-z0-9]+", "_", value.lower())).strip("_")


def _ident(value: str) -> str:
    return "".join(part.capitalize() for part in _slug(value).split("_"))


def _cpp_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def build_view_specs(config: ocio.Config) -> list[dict]:
    available_looks = {look.getName() for look in config.getLooks()}
    specs: list[dict] = []
    seen_names: set[str] = set()

    for output in LUT_OUTPUTS:
        display = output["display"]
        available_views = set(config.getViews(display))
        for view, looks in LUT_SELECTIONS[output["kind"]]:
            if view not in available_views:
                raise ValueError(f"Display '{display}' has no view '{view}'. Available views: {sorted(available_views)}")
            for look in looks:
                if look is not None and look not in available_looks:
                    raise ValueError(f"OCIO config has no look '{look}'. Available looks: {sorted(available_looks)}")

                look_slug = "no_look" if look is None else f"look_{_slug(look)}"
                name = f"view_lut_{output['kind']}_{_slug(view)}_{look_slug}"
                if name in seen_names:
                    raise ValueError(f"Duplicate LUT name generated: {name}")
                seen_names.add(name)

                label = f"{view} / {'No Look' if look is None else look}"
                specs.append({
                    "kind": output["kind"],
                    "display": display,
                    "view": view,
                    "look": look,
                    "name": name,
                    "ident": f"kViewLut{_ident(output['kind'])}{_ident(view)}{_ident(look_slug)}",
                    "label": label,
                    "path": f"data/assets/{name}.dds",
                })

    return specs


def write_view_luts_header(path: Path, views: list[dict], config_path: Path) -> None:
    lines: list[str] = []
    lines.append(f"// Generated by Scripts/{Path(__file__).name}")
    lines.append(f"// OCIO config: {config_path}")
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("struct ViewLUTEntry")
    lines.append("{")
    lines.append("    const char* label;")
    lines.append("    const char* path;")
    lines.append("};")
    lines.append("")

    for output in LUT_OUTPUTS:
        output_views = [view for view in views if view["kind"] == output["kind"]]
        if not output_views:
            raise ValueError(f"No LUTs generated for {output['kind']}")

        lines.append(f"inline constexpr ViewLUTEntry {output['array_name']}[] = {{")
        for view in output_views:
            lines.append(f"    {{\"{_cpp_string(view['label'])}\", \"{_cpp_string(view['path'])}\"}},")
        lines.append("};")
        lines.append("")

        lines.append(
            f"inline constexpr int {output['count_name']} = "
            f"static_cast<int>(sizeof({output['array_name']}) / sizeof({output['array_name']}[0]));"
        )
        default_index = next(
            (
                index for index, view in enumerate(output_views)
                if view["view"] == output["default_view"] and view["look"] == output["default_look"]
            ),
            None,
        )
        if default_index is None:
            raise ValueError(f"Default LUT not found for {output['kind']}")
        lines.append(f"inline constexpr int {output['default_name']} = {default_index};")
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def print_summary(config_path: Path, views: list[dict], output_dir: Path) -> None:
    print(f"Using OCIO {ocio.__version__}")
    print(f"Config: {config_path}")
    print(f"Input:  {DEFAULT_INPUT_SPACE}")
    print("Shaper: BT.709/D65 -> AP1/D60 Bradford -> ACEScct (raw [0,1] LUT domain)")
    print(f"Size:   {DEFAULT_LUT_SIZE}^3, DDS RGB10A2 UNORM")
    print(f"Views:  {len(views)} ({sum(1 for view in views if view['kind'] == 'sdr')} SDR, "
          f"{sum(1 for view in views if view['kind'] == 'hdr')} HDR)")
    print(f"Output: {output_dir}")


def print_configured_targets(views: list[dict]) -> None:
    for view in views:
        look = "No Look" if view["look"] is None else view["look"]
        print(f"{view['name']}: {view['display']} / {view['view']} / {look}")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Bake all Foundation Blender OCIO view LUTs and regenerate ViewLUTs.hpp.",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=FOUNDATION_OCIO_CONFIG,
        help="OCIO config path, default: Scripts/blender-5-1-colormanagement/config.ocio",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DDS_OUTPUT_DIR,
        help="Output DDS directory, default: Editor/Render/Data",
    )
    parser.add_argument("--list", action="store_true", help="List configured bake targets, then exit")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    config = create_config(args.config)
    views = build_view_specs(config)

    if args.list:
        print_configured_targets(views)
        return

    print_summary(args.config, views, args.output_dir)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    for stale in args.output_dir.glob("view_lut_*.dds"):
        stale.unlink()

    for view in views:
        output_path = args.output_dir / f"{view['name']}.dds"
        bake_args = [
            str(output_path),
            "--config", str(args.config),
            "--display", view["display"],
            "--view", view["view"],
            "--input-space", DEFAULT_INPUT_SPACE,
            "--size", str(DEFAULT_LUT_SIZE),
        ]
        if view["look"] is not None:
            bake_args.extend(["--look", view["look"]])

        bake_ocio_lut_main(bake_args)

    write_view_luts_header(VIEW_LUTS_HEADER_PATH, views, args.config)
    print(f"\nwrote {VIEW_LUTS_HEADER_PATH}")


if __name__ == "__main__":
    main()
