from PIL import Image, ImageFont, ImageDraw

TEXTURE_WIDTH = 1024
BW_THRESHOLD = 128

FONT_HEIGHT = 16
font_path = "Data/Perfect DOS VGA 437.ttf"

font = ImageFont.truetype(font_path, FONT_HEIGHT)
char_set = [chr(i) for i in range(ord(' '), 256)]  # Printable ASCII + extended
atlas = Image.new('L', (TEXTURE_WIDTH, FONT_HEIGHT + 1), 0) # shadow V
u_offsets = [0] * 256

u = 0
width_min = TEXTURE_WIDTH # Monospace
for char in char_set:    
    bbox = font.getbbox(char)
    width, height = bbox[2] - bbox[0], bbox[3] - bbox[1]
    char_img = Image.new('L', (width, FONT_HEIGHT), 0)    
    draw = ImageDraw.Draw(char_img)
    draw.text((0, FONT_HEIGHT), char, anchor='ld', font=font, fill=255)

    atlas.paste(char_img, (u, 0))
    if u + width > TEXTURE_WIDTH:
        break
    u_offsets[ord(char)] = u
    u += width + 1 # shadow U
    width_min = min(width_min, width)

#  U offset
desc = []
for i in range(0, 256, 2):
    u1 = u_offsets[i] & 0xFFFF
    u2 = u_offsets[i+1] & 0xFFFF
    packed_val = (u1 << 16) | u2
    desc.append(packed_val)

tex = []
for i in range(0, TEXTURE_WIDTH * FONT_HEIGHT, 32):
    packed_val = 0
    for j in range(32):
        bit_index = i + j
        x = bit_index % TEXTURE_WIDTH
        y = bit_index // TEXTURE_WIDTH    
        pixel = atlas.getpixel((x, y))
        if pixel > BW_THRESHOLD:
            packed_val |= (1 << (31 - j))
            atlas.putpixel((x,y), 255)
        else:
            atlas.putpixel((x,y), 0)
    tex.append(packed_val)
print('/** vvv Auto-generated by Scripts/CSDebugTextFont.py vvv **/')
print(f'const static int kFontW = {width_min}, kFontH = {FONT_HEIGHT};')
print('''// glyph U offset (0-1023) for each ASCII character (uint16), packed into uint''')
print("const static uint gGlyphUOffset[256*2/4] = {")
for i in range(0, len(desc), 8):
    line = ", ".join(f"0x{val:08x}" for val in desc[i:i+8])
    print(f"\t{line},")
print("};")
print(f'''
// a 1024x{FONT_HEIGHT} texture, packed in raster order into bits:
// each byte encodes a pixel in each bit
// offsets into this data come from font description above''')
print("const static uint gGlyphBitmap[1024*kFontH/32] = {")
for i in range(0, len(tex), 8):
    line = ", ".join(f"0x{val:08x}" for val in tex[i:i+8])
    print(f"\t{line},")
print("};")
print('/** ^^^ Auto-generated by Scripts/CSDebugTextFont.py ^^^ **/')
atlas.show()