#ifndef FOUNDATION_DEFINES
#define FOUNDATION_DEFINES
// NOTE : pch.hpp includes this file so editing it causes a complete rebuild.
#define FOUNDATION_VERSION_MAJOR 0
#define FOUNDATION_VERSION_MINOR 0
#define FOUNDATION_VERSION_PATCH 0
#define FOUNDATION_VERSION_SPECIAL "/poc"
// https://stackoverflow.com/a/6990647
#define QU(x) #x
#define QUH(x) QU(x)
#define FOUNDATION_VERSION_STRING QUH(FOUNDATION_VERSION_MAJOR) "." QUH(FOUNDATION_VERSION_MINOR) "." QUH(FOUNDATION_VERSION_PATCH) "" FOUNDATION_VERSION_SPECIAL

#define IMGUI_ENABLED

#define RHI_USE_D3D12
#define RHI_D3D12_USE_AGILITY
// #define RHI_USE_MESH_SHADER

#define RHI_DEFAULT_SWAPCHAIN_BACKBUFFER_COUNT 3
#define RHI_DEFAULT_DIRECT_COMMAND_ALLOCATOR_COUNT RHI_DEFAULT_SWAPCHAIN_BACKBUFFER_COUNT
#define RHI_DEFAULT_COPY_COMMAND_ALLOCATOR_COUNT 1
#define RHI_DEFAULT_COMPUTE_COMMAND_ALLOCATOR_COUNT 1
#define RHI_ALLOC_SIZE_DESCHEAP 0xffff
#define RHI_ALLOC_SIZE_SHADER_VISIBLE_DESCHEAP 2048
#endif
